tag_prefix = "v"

pre_bump_hooks = [
  "bun run scrape",
  "bun run build",
  "npm version {{version}} --no-git-tag-version --allow-same-version",
]

post_bump_hooks = [
  "git push",
  "git push origin {{version_tag}}",
  "gh release create {{version_tag}} --notes \"$(cog changelog --at {{version_tag}})\"",
]
