disable_changelog = true

tag_prefix = "v"

pre_bump_hooks = [
  "npm version {{version}} --no-git-tag-version --allow-same-version",
]

post_bump_hooks = [
  "git push",
  "git push origin {{version_tag}}",
]
